// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	subscribeFieldNames          = builder.RawFieldNames(&Subscribe{})
	subscribeRows                = strings.Join(subscribeFieldNames, ",")
	subscribeRowsExpectAutoSet   = strings.Join(stringx.Remove(subscribeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	subscribeRowsWithPlaceHolder = strings.Join(stringx.Remove(subscribeFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	subscribeModel interface {
		Insert(ctx context.Context, data *Subscribe) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Subscribe, error)
		Update(ctx context.Context, data *Subscribe) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultSubscribeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Subscribe struct {
		Id         uint64    `db:"id"`
		UserId     uint64    `db:"user_id"`
		SubjectId  uint64    `db:"subject_id"`
		CreateTime time.Time `db:"create_time"`
		CreateId   uint64    `db:"create_id"`
		UpdateTime time.Time `db:"update_time"`
		UpdateId   uint64    `db:"update_id"`
	}
)

func newSubscribeModel(conn sqlx.SqlConn) *defaultSubscribeModel {
	return &defaultSubscribeModel{
		conn:  conn,
		table: "`subscribe`",
	}
}

func (m *defaultSubscribeModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSubscribeModel) FindOne(ctx context.Context, id uint64) (*Subscribe, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", subscribeRows, m.table)
	var resp Subscribe
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSubscribeModel) Insert(ctx context.Context, data *Subscribe) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, subscribeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.SubjectId, data.CreateId, data.UpdateId)
	return ret, err
}

func (m *defaultSubscribeModel) Update(ctx context.Context, data *Subscribe) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, subscribeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.SubjectId, data.CreateId, data.UpdateId, data.Id)
	return err
}

func (m *defaultSubscribeModel) tableName() string {
	return m.table
}
