// Code generated by goctl. DO NOT EDIT.

export interface AddUserRequest {
	name: string
	nick_name: string
	email: string
	password: string
	group_id: number
}

export interface AddUserResponse {
}

export interface CreateGroupRequest {
	name: string
}

export interface CreateGroupResponse {
	id: number
}

export interface CreateScoreRequest {
	user_id: number
	group_id: number
	score: number
	subject_id: number
}

export interface CreateScoreResponse {
	id: number
}

export interface CreateSubjectRequest {
	name: string
	description: string
	due_date: number
	score: number
	accept: string
}

export interface CreateSubjectResponse {
	id: number
}

export interface CreateSubscribeRequest {
	user_id: number
	subject_id: number
}

export interface CreateSubscribeResponse {
	id: number
}

export interface DeleteGroupRequest {
	id: number
}

export interface DeleteGroupResponse {
}

export interface DeleteScoreRequest {
	id: number
}

export interface DeleteScoreResponse {
}

export interface DeleteSubjectRequest {
	ids: Array<number>
}

export interface DeleteSubjectResponse {
}

export interface DeleteSubscribeRequest {
	ids: Array<number>
}

export interface DeleteSubscribeResponse {
}

export interface DeleteUserRequest {
	ids: Array<number>
}

export interface DeleteUserResponse {
}

export interface Group {
	id: number
	name: string
}

export interface GroupDetailRequest {
}
export interface GroupDetailRequestParams {
}

export interface GroupListFilter {
	name?: string
}

export interface GroupListRequest {
	page_num: number
	page_size: number
	filters?: GroupListFilter
}

export interface GroupListResponse {
	total: number
	page_num: number
	list: Array<Group>
}

export interface LoginRequest {
	email: string
	password: string
}

export interface LoginResponse {
	accessToken: string
}

export interface RegisterRequest {
	name: string
	nick_name: string
	email: string
	password: string
	group_id: number
}

export interface RegisterResponse {
}

export interface Score {
	id: number
	user_id: number
	group_id: number
	score: number
	subject_id: number
	create_id: number
	create_time: number
	update_id: number
	update_time: number
}

export interface ScoreDetailRequest {
}
export interface ScoreDetailRequestParams {
}

export interface ScoreListFilter {
	user_id?: number
	group_id?: number
	subject_id?: number
}

export interface ScoreListRequest {
	page_num: number
	page_size: number
	filter?: ScoreListFilter
}

export interface ScoreListResponse {
	total: number
	page_num: number
	list: Array<Score>
}

export interface Subject {
	id: number
	name: string
	description: string
	due_date: number
	score: number
	accept: string
	create_id: number
	create_time: number
}

export interface SubjectDetailRequest {
}
export interface SubjectDetailRequestParams {
}

export interface SubjectListFilter {
	name?: string
	accept?: string
}

export interface SubjectListRequest {
	pageNum: number
	pageSize: number
	filters?: SubjectListFilter
}

export interface SubjectListResponse {
	total: number
	pageNum: number
	list: Array<Subject>
}

export interface Subscribe {
	id: number
	user_id: number
	subject_id: number
	create_id: number
	create_time: number
	update_id: number
	update_time: number
}

export interface SubscribeDetailRequest {
}
export interface SubscribeDetailRequestParams {
}

export interface SubscribeListFilter {
	subject_id?: number
	user_id?: number
}

export interface SubscribeListRequest {
	page_num: number
	page_size: number
	filters?: SubscribeListFilter
}

export interface SubscribeListResponse {
	total: number
	page_num: number
	list: Array<Subscribe>
}

export interface UpdateGroupRequest {
	id: number
	name: string
}

export interface UpdateGroupResponse {
	id: number
}

export interface UpdateScoreRequest {
	id: number
	score: number
	user_id: number
	group_id: number
	subject_id: number
}

export interface UpdateScoreResponse {
}

export interface UpdateSubjectRequest {
	id: number
	name: string
	description: string
	due_date: number
	score: number
	accept: string
}

export interface UpdateSubjectResponse {
}

export interface UpdateSubscribeRequest {
	id: number
	user_id: number
	subject_id: number
}

export interface UpdateSubscribeResponse {
	id: number
}

export interface UpdateUserDetailRequest {
	name: string
	nick_name: string
	group_id: number
}

export interface UpdateUserDetailResponse {
}

export interface UpdateUserPasswordRequest {
	oldPassword: string
	newPassword: string
}

export interface UpdateUserPasswordResponse {
}

export interface UpdateUserRequest {
	id: number
	name: string
	nick_name: string
	email: string
	password: string
	group_id: number
}

export interface UpdateUserResponse {
}

export interface User {
	id: number
	name: string
	nick_name: string
	email: string
	type: string
	password: string
	group_id: number
	active_flag: string
	create_time: number
}

export interface UserDetailRequest {
}
export interface UserDetailRequestParams {
}

export interface UserDetailResponse {
	id: number
	name: string
	nick_name: string
	password: string
	group_id: number
}

export interface UserListFilter {
	name?: string
	nick_name?: string
	email?: string
	type?: string
	group_id?: number
}

export interface UserListRequest {
	pageNum: number
	pageSize: number
	filters?: UserListFilter
}

export interface UserListResponse {
	total: number
	pageNum: number
	list: Array<User>
}

export interface UserName {
	id: number
	name: string
}

